const paketData = [
    {   id: 1,
        title: "Rafatour dolphin & snorkeling",
        slug: "rafatour-dolphin-&-snorkeling",
        imageSrc: "/paket-rafatour-dolphine-snorkling.png",
        price: "Rp. 300.000",
        rating: 4.7,
        reviews: 45,
        duration: "3-4 Jam",
        capacity: "Maksimal 10 orang/perahu",
        desk: [
        "Pengalaman melihat lumba-lumba",
        "Pengalaman berenang dengan lumba-lumba",
        "Snorkeling",
        "Pelampung keselamatan",
        "Pemandu lokal berpengalaman",
        ],
        schedule: "Setiap hari",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 1 jam – Termasuk minuman ringan",
        departurTime: "05.30 WITA",
    },
    
    {   id: 2,
        title: "Seadolphine Lovina",
        slug: "seadolphine-lovina",
        imageSrc: "/paket-seadolphine-lovina.png",
        price: "Rp. 350.000",
        rating: 4.5,
        reviews: 45,
        duration: "2-3 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Pengalaman melihat lumba-lumba",
        "Berenang bersama lumba-lumba",
        "Snorkeling di Lovina",
        "Perlengkapan snorkeling",
        "Pelampung",
        "Captain dan pemandu",
        ],
        schedule: "Setiap hari, pukul 08.00 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 2 jam - Termasuk snack & minum",
        departurTime: "05.30 WITA",
    },
    
    {   id: 3,
        title: "Watching Dolphin Only",
        slug: "watching-dolphin-only",
        imageSrc: "/paket-watching-dolphine-only.png",
        price: "Rp. 100.000",
        rating: 4.4,
        reviews: 54,
        duration: "2 Jam",
        capacity: "Maksimal 8-10 orang/perahu",
        desk: [
        "Perahu sharing",
        "Pelampung keselamatan",
        "Pemandu",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 2 jam - Termasuk pelampung & guide",
        departurTime: "05.30 WITA",
    },
    
    {   id: 4,
        title: "Snorkeling & Dolphin Tur",
        slug: "snorkeling-&-dolphin-tur",
        imageSrc: "/paket-snorkling-tur.png",
        price: "Rp. 350.000",
        rating: 4.4,
        reviews: 54,
        duration: "2 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Satu botol mineral untuk setiap peserta",
        "Menikmati minuman selamat datang khas Bali (Teh atau kopi) setibanya di Pantai Lovina",
        "Peralatan snorkeling",
        "Pemandu lokal berpengalaman",
        "Dokumentasi kegiatan (Foto dan Video)",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 3 jam - Termasuk minuman hangat",
        departurTime: "05.30 WITA",
    },
    
    {   id: 5,
        title: "Dolphin Watching Tur",
        slug: "dolphin-watching-tur",
        imageSrc: "/dolphinWatchingTour.jpg",
        price: "Rp. 200.000",
        rating: 4.4,
        reviews: 40,
        duration: "3 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Pengalaman berenang dengan lumba-lumba saat matahari terbit",
        "Minuman hangat diatas perahu",
        "Pelampung keselamatan",
        "Pemandu lokal berpengalaman",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 1,5 jam - Termasuk pelampung",
        departurTime: "05.30 WITA",
    },
    
    {   id: 6,
        title: "Swim with Dolphin",
        slug: "swim-with-dolphin",
        imageSrc: "/swimWithDolphin.jpg",
        price: "Rp. 200.000",
        rating: 4.6,
        reviews: 38,
        duration: "1,5 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Pengalaman berenang dengan lumba-lumba saat matahari terbit",
        "Air mineral",
        "Pelampung keselamatan",
        "Pamandu lokal berpengalaman",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 2 jam - Termasuk satu perahu khusus",
        departurTime: "05.30 WITA",
    },
    
    {   id: 7,
        title: "Private Tour Guide",
        slug: "private-tour-guide",
        imageSrc: "/privateTourGuide.png",
        price: "Rp. 400.000",
        rating: 4.5,
        reviews: 40,
        duration: "2 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "1 Perahu khusus pribadi hanya untuk Anda dan rombongan",
        "Pengalaman ekslusif menyaksikan lumba-lumba",
        "Pelampung keselamatan",
        "Private guide lokal berpengalaman yang mendampongi penuh selama tur",
        "Air mineral & snack ringan diatas perahu",
        ],
        schedule: "Setiap hari, pukul 07.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 2 jam - Termasuk satu perahu khusus",
        departurTime: "05.30 WITA",
    },
    
    {   id: 8,
        title: "Snorkeling Lovina",
        slug: "snorkeling-lovina",
        imageSrc: "/paket-snorkeling-lovina.png",
        price: "Rp. 150.000",
        rating: 4.2,
        reviews: 39,
        duration: "2 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Peralatan snorkeling lengkap (masker, snorkel, fin)",
        "Pelampung keselamatan",
        "Pemandu lokal berpengalaman",
        "Pengalaman snorkeling di spot terbaik lovina",
        ],
        schedule: "Setiap hari, pukul 08.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "Durasi 2 jam",
        departurTime: "05.30 WITA",
    },
    
    {   id: 9,
        title: "Bali Surga Private Tour Lovina With Dolphin Tour",
        shortTitle : "Bali Surga Private Tour Dolphin",
        slug: "bali-surga-private-tour-lovina-with-dolphin-tour",
        imageSrc: "/paket-bali-surga(1).webp",
        price: "Rp. 600.000",
        rating: 3.5,
        reviews: 38,
        duration: "2 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Private boat",
        "Air mineral untuk setiap peserta",
        "Pelampung keselamatan",
        "Pemandu lokal berpengalaman",
        "Pengalaman snorkeling di spot terbaik Lovina",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "",
        departurTime: "05.30 WITA",
    },
    
    {   id: 10,
        title: "Sharing Tour Lovina Ocean Tour Sunrise Dolphin Tour",
        shortTitle : "Sharing Tour Lovina Ocean Tour",
        slug: "sharing-tour-lovina-ocean-tour-sunrise-dolphin-tour",
        imageSrc: "/paket-lovina-ocean-tour.webp",
        price: "Rp. 100.000",
        rating: 4.0,
        reviews: 38,
        duration: "2 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Perjalanan sunrise melihat lumba-lumba di Laut Lovina",
        "Perahu sharing bersama peserta lain",
        "Pemandu lokal berpengalaman",
        "Pelampung keselamatan tersedia untuk setiap peserta",
        "Pengalaman menikmati keindahan matahari terbit di Lovina",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "",
        departurTime: "05.30 WITA",
    },
    
    {   id: 11,
        title: "Private Tour Lovina Ocean Tour Sunrise Dolphin Tour",
        shortTitle : "Private Tour Lovina Ocean Tour",
        slug: "private-tour-lovina-ocean-tour-sunrise-dolphin-tour",
        imageSrc: "/paket-lovina-ocean-private-tour.webp",
        price: "Rp. 150.000",
        rating: 4.5,
        reviews: 38,
        duration: "2 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Perjalanan sunrise melihat lumba-lumba di Laut Lovina",
        "Perahu khusus private boat",
        "Pemandu lokal berpengalaman",
        "Pelampung keselamatan tersedia untuk setiap peserta",
        "Pengalaman menikmati keindahan matahari terbit di Lovina",
        ],
        schedule: "Setiap hari, pukul 05.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "",
        departurTime: "05.30 WITA",
    },
    
    // {   id: 12,
    //     title: "Sharing Tour Paket Dolphin Watching Swim & Snorkling",
    //     slug: "sharing-tour-paket-dolphin-watching-swim-&-snorkling",
    //     imageSrc: "/paket-dolphin-watching-swim-snorkling.webp",
    //     price: "Rp. 300.000",
    //     rating: 4.5,
    //     reviews: 38,
    //     duration: "3 Jam",
    //     capacity: "Maksimal 5 orang/perahu",
    //     desk: [
    //     "Berenang bersama lumba-lumba di area yang diizinkan",
    //     "Peralatan snorkeling lengkap (masker, snorkel, fin)",
    //     "Pelampung keselamatan untuk setiap peserta",
    //     "Tur dengan perahu sharing bersama peserta lain",
    //     "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan",
    //     ],
    //     schedule: "Setiap hari, pukul 08.30 WITA",
    //     location: "Pantai Lovina, Bali",
    //     tagLine: "",
    //     departurTime: "08.30 WITA",
    // },
    
    {   id: 13,
        title: "Private Tour Paket Dolphin Watching Swim & Snorkling",
        shortTitle : "Private Tour Paket Dolphin Watching",
        slug: "private-tour-paket-dolphin-watching-swim-&-snorkling",
        imageSrc: "/paket-dolphin-watching-swim-snorkling-private.webp",
        price: "Rp. 350.000",
        rating: 4.5,
        reviews: 38,
        duration: "3 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Berenang bersama lumba-lumba di area yang diizinkan",
        "Peralatan snorkeling lengkap (masker, snorkel, fin)",
        "Pelampung keselamatan untuk setiap peserta",
        "Perahu khusus private boat",
        "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan",
        ],
        schedule: "Setiap hari, pukul 08.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "",
        departurTime: "08.30 WITA",
    },

    {   id: 14,
        title: "Paon Happy Sharing Boat Watching Dolphin Only",
        shortTitle : "Paon Happy Sharing Boat Dolphin",
        slug: "paon-happy-sharing-boat-watching-dolphin-only",
        imageSrc: "/paket-paon-happy-sharing-boat-watching-dolphin.webp",
        price: "Rp. 200.000",
        rating: 4.5,
        reviews: 38,
        duration: "3 Jam",
        capacity: "Maksimal 5 orang/perahu",
        desk: [
        "Perjalanan sunrise melihat lumba-lumba di Laut Lovina",
        "Pelampung keselamatan untuk setiap peserta",
        "Perahu khusus private boat",
        "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan",
        ],
        schedule: "Setiap hari, pukul 08.30 WITA",
        location: "Pantai Lovina, Bali",
        tagLine: "",
        departurTime: "08.30 WITA",
    },

    { id: 15, 
      title: "Paon Happy Sharing Boat Watching Dolphin (Breakfast)",
      shortTitle : "Paon Happy Sharing Boat Breakfast",
      slug: "paon-happy-sharing-boat-watching-dolphin-(breakfast)", 
      imageSrc: "/paket-paon-happy-watching-dolphin-breakfast.jpg",
      price: "Rp. 130.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "1,5 Jam", 
      capacity: "Maksimal 5 orang/perahu", 
      desk: [ 
      "Sarapan pagi sebelum keberangkatan", 
      "Perjalanan melihat lumba-lumba menggunakan perahu sharing", 
      "Mengamati lumba-lumba di habitat aslinya tanpa berenang bersama", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" 
      ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali", 
      tagLine: "", 
      departurTime: "08.30 WITA" },
    
    { id: 16, 
      title: "Paon Happy Sharing Boat Watching Dolphin (Swimming)",
      shortTitle : "Paon Happy Sharing Boat Swimming",
      slug: "paon-happy-sharing-boat-watching-dolphin-(swimming)", 
      imageSrc: "/paon-happy-watching-dolphin-swimming.jpg",
      price: "Rp. 350.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "2 Jam", 
      capacity: "Maksimal 5 orang/perahu", 
      desk: [ 
      "Berenang bersama lumba-lumba pada area yang diizinkan", 
      "Perjalanan melihat lumba-lumba menggunakan perahu sharing", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" 
      ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali", 
      tagLine: "", 
      departurTime: "08.30 WITA" 
    },

    { id: 17, 
      title: "Paon Happy Private Boat Watching Dolphin (Snorkling)",
      shortTitle : "Paon Happy Private Boat Snorkling",
      slug: "paon-happy-private-boat-watching-dolphin-(snorkling)", 
      imageSrc: "/paket-paon-happy-watching-dolphin-snorkling.jpg",
      price: "Rp. 200.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "2,5 Jam", 
      capacity: "Maksimal 5 orang/perahu", 
      desk: [ 
      "Snorkling pada area yang diizinkan", 
      "Perjalanan melihat lumba-lumba menggunakan perahu sharing", 
      "Mengamati lumba-lumba di habitat aslinya tanpa berenang bersama", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" 
      ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali", 
      tagLine: "", 
      departurTime: "08.30 WITA" 
    },

    { id: 18, 
      title: "Paon Happy Private Boat Watching Dolphin",
      slug: "paon-happy-private-boat-watching-dolphin", 
      imageSrc: "/paket-paon-happy-sharing-boat-watching-dolphin-only.webp",
      price: "Rp. 450.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "3 Jam", 
      capacity: "Minimal 2 orang/perahu", 
      desk: [ 
      "Perjalanan melihat lumba-lumba", 
      "Snorkling dan berenang bersama lumba-lumba pada area yang diizinkan", 
      "Sarapan pagi sebelum keberangkatan", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" 
      ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali", 
      tagLine: "", 
      departurTime: "08.30 WITA" 
    },


    { id: 19, 
      title:"Paon Happy Private Boat Watching",
      slug: "paon-happy-private-boat-watching", 
      imageSrc: "/paon-happy-private-boat-2-person-only.webp", 
      price: "Rp. 400.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "2,5 Jam", 
      capacity: "Hanya 2 orang/perahu", 
      desk: [ 
      "Additional 1 orang 100/orang", 
      "Perjalanan melihat lumba-lumba", 
      "Mengamati lumba-lumba di habitat aslinya tanpa berenang bersama", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" 
      ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali", 
      tagLine: "", 
      departurTime: "08.30 WITA" 
    },
    
    { id: 20, 
      title: "Saraswati Tour Sunrise Dolphine", 
      slug: "saraswati-tour-sunrise-dolphine", 
      imageSrc: "/paket-sarawasti-sunrise-watching.jpeg",
      price: "Rp. 100.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "2-3 Jam", 
      capacity: "Maksimal 5 orang/perahu", 
      desk: [ 
      "Perjalanan melihat lumba-lumba", 
      "Mengamati lumba-lumba di habitat aslinya tanpa berenang bersama", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" 
      ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali", 
      tagLine: "", 
      departurTime: "08.30 WITA" 
    },

    { id: 21, 
      title: "Saraswati Tour Lovina Snorkling", 
      slug: "saraswati-tour-lovina-snorkling", 
      imageSrc: "/paket-saraswati-lovina-snorkling.jpeg", 
      price: "Rp. 100.000", 
      rating: 4.5, 
      reviews: 38, 
      duration: "2-3 Jam", 
      capacity: "Maksimal 5 orang/perahu", 
      desk: [ 
      "Perjalanan melihat lumba-lumba", 
      "Mengamati lumba-lumba di habitat aslinya tanpa berenang bersama", 
      "Pelampung keselamatan tersedia untuk setiap peserta", 
      "Pemandu lokal berpengalaman untuk memastikan keamanan dan kenyamanan", 
      "Tur santai dengan perahu sharing bersama peserta lain" ], 
      schedule: "Setiap hari, pukul 08.30 WITA", 
      location: "Pantai Lovina, Bali",
      tagLine: "", 
      departurTime: "08.30 WITA" 
    },

];

export default paketData;
    