    const cardReviewPaket6 = [
        // {
        //     id: 1,
        //     paketId: 6,
        //     avatar: "/paket6(2).jpg",
        //     username: 'Nadia',
        //     rating: 4,
        //     tanggalBerangkat: "2025-09-13",
        //     title: "Swim with Dolphin",
        //     text: "Pengalaman berenang sama lumba-lumba bener-bener nggak bisa dilupain! Airnya jernih dan pemandunya sabar banget ngarahin kami. Durasi 1,5 jam terasa pas dan aman karena semua sudah disiapin, termasuk pelampung. Recommended banget buat yang suka aktivitas pagi.",
        //     likes: 10,
        //     images: ["/reviewPaket6A(1).jpg", "/reviewPaket6A(2).jpg"],
        // },
        // {
        //     id: 2,
        //     paketId: 6,
        //     avatar: "/paket6(1).jpg",
        //     username: 'Kevindive',
        //     rating: 5,
        //     tanggalBerangkat: "2025-09-13",
        //     title: "Swim with Dolphin",
        //     text: "Seru banget! Lumba-lumbanya muncul cukup dekat dan kami bisa berenang bareng dengan aman. Air mineral disediakan dan pemandunya sangat profesional. Cuma waktunya terasa cepat saking serunya, tapi tetap worth it buat pengalaman langka seperti ini.",
        //     likes: 9,
        //     images: ["/reviewPaket6B(1).jpg"],
        // },
        // {
        //     id: 3,
        //     paketId: 6,
        //     avatar: "/paket6(3).jpg",
        //     username: 'Maya',
        //     rating: 4,
        //     tanggalBerangkat: "2025-09-01",
        //     title: "Swim with Dolphin",
        //     text: "Aktivitas ini menyenangkan dan cocok buat yang mau coba hal baru. Pemandu lokalnya ramah dan bikin suasana nyaman. Pelampung juga disediakan jadi aman untuk pemula. Ombaknya sedikit tinggi waktu itu, tapi keseluruhannya tetap pengalaman yang menyenangkan!",
        //     likes: 10,
        //     images: [],
        // },
    ];

    export default cardReviewPaket6;