    const cardReviewPaket3 = [
        {
            id: 1,
            paketId: 3,
            avatar: "/paket3(1).jpg",
            username: 'Cherie A',
            rating: 4,
            tanggalBerangkat: "2025-10-10",
            title: "Watching Dolphin Only",
            text: "Petualangan paling menakjubkan bersama keluarga saya. Saya sangat merekomendasikannya! Keluarga saya dan saya memiliki pengalaman terbaik. Begitu banyak lumba-lumba!",
            likes: 10,
            images: ["/reviewPaket3A(1).jpg", "/reviewPaket3A(2).jpeg"],
        },
        {
            id: 2,
            paketId: 3,
            avatar: "/paket3(2).jpg",
            username: 'Nichole Van',
            rating: 4,
            tanggalBerangkat: "2025-10-10",
            title: "Watching Dolphin Only",
            text: "Sore ini dimulai dengan perjalanan yang luar biasa ini, matahari terbit di atas laut sudah sangat indah. Tapi melihat banyak lumba-lumba dari dekat sungguh menakjubkan",
            likes: 10,
            images: ["/reviewPaket3B(1).jpg"],
        },
        {
            id: 3,
            paketId: 3,
            avatar: "/paket3(3).jpg",
            username: 'Traveling with Kim',
            rating: 4,
            tanggalBerangkat: "2025-09-15",
            title: "Watching Dolphin Only",
            text: "Pengalaman yang luar biasa dan akan menjadi salah satu kenangan terbaik dalam hidup kami! 🐬",
            likes: 10,
            images: [],
        },
        {
            id: 4,
            paketId: 3,
            avatar: "/paket3(4).jpg",
            username: 'Ellie M',
            rating: 4,
            tanggalBerangkat: "2025-09-15",
            title: "Watching Dolphin Only",
            text: "Itu benar-benar pengalaman yang luar biasa! Kami melihat banyak lumba-lumba dan semua orang punya banyak waktu untuk menonton mereka!!",
            likes: 10,
            images: [],
        },
    ];

    export default cardReviewPaket3;