    const cardReviewPaket4 = [
        {
            id: 1,
            paketId: 4,
            avatar: "/paket4(1).jpg",
            username: 'Kimberly',
            rating: 4,
            tanggalBerangkat: "2025-09-13",
            title: "Snorkeling & Dolphin Tur",
            text: "Kapten jelas tahu spot terbaik untuk menemukan lumba-lumba. Untuk tur yang tidak menguras kantong, hasilnya sungguh mengesankan.",
            likes: 20,
            images: [],
        },
        {
            id: 2,
            paketId: 4,
            avatar: "/paket4(2).jpg",
            username: 'Shalley',
            rating: 4,
            tanggalBerangkat: "2025-09-13",
            title: "Snorkeling & Dolphin Tur",
            text: "Peralatan snorkling yang disediakan bersih dan nyaman digunakan, yang membuat pengalaman ini semakin menyenangkan. Jika Anda menyukai aktivitas bawah air, tur ini pasti worth it.",
            likes: 12,
            images: ["/reviewPaket4B(1).jpg", "/reviewPaket4B(2).jpg"],
        },
        {
            id: 3,
            paketId: 4,
            avatar: "/paket4(3).jpg",
            username: 'Bobby Thomson',
            rating: 4,
            tanggalBerangkat: "2025-09-13",
            title: "Snorkeling & Dolphin Tur",
            text: "Tim dari Tour Guide benar-benar luar biasa! perahu dalam kondisi bersih, dan jaket pelampung disediakan untuk semua orang. Kapten dengan sabar menunggu momen terbaik untuk melihat lumba-lumba. Semua perlengkapan snorkeling juga dalam kondisi baik.",
            likes: 5,
            images: ["/reviewPaket4C(1).jpg", "/reviewPaket4C(2).webp"],
        },
        {
            id: 4,
            paketId: 4,
            avatar: "/paket4(4).jpg",
            username: 'Erika',
            rating: 4,
            tanggalBerangkat: "2025-09-03",
            title: "Snorkeling & Dolphin Tur",
            text: "Ini benar-benar pengalaman yang tak terlupakan. Saat pertama kali memesan, kami tidak yakin apa yang akan kami dapatkan, terutama karena tidak banyak ulasan yang tersedia. Ternyata, ini menjadi salah satu momen favorit kami selama perjalanan.",
            likes: 3,
            images: [],
        },
        {
            id: 5,
            paketId: 4,
            avatar: "/paket4(5).jpg",
            username: 'Travelleradam',
            rating: 4,
            tanggalBerangkat: "12025-09-01",
            title: "Snorkeling & Dolphin Tur",
            text: "Pengalaman snorkling yang sangat luar biasa",
            likes: 8,
            images: [],
        },
        {
            id: 6,
            paketId: 4,
            avatar: "/paket4(6).jpg",
            username: 'Alan',
            rating: 4,
            tanggalBerangkat: "2025-09-01",
            title: "Snorkeling & Dolphin Tur",
            text: "Pengalaman yang sangat berkesan",
            likes: 10,
            images: ["/reviewPaket4F(1).jpg",],
        },
    ];

    export default cardReviewPaket4;