    const cardReviewPaket13 = [
        // {
        //     id: 1,
        //     paketId: 13,
        //     avatar: "/felix.jpg",
        //     username: 'felix Wanderlust',
        //     rating: 5,
        //     tanggalBerangkat: "2025-08-03",
        //     title: "Paon Happy Sharing Boat Watching Dolphin Only",
        //     text: "Pengalaman melihat lumba-lumba di Lovina pagi-pagi benar-benar tak terlupakan! Perahu privat membuat tur lebih nyaman dan pemandunya sangat berpengalaman, selalu memastikan keselamatan kami. Sunrise pagi itu juga luar biasa indah. Sangat direkomendasikan untuk yang ingin tur tenang dan eksklusif.",
        //     likes: 10,
        //     images: ["/felix1.jpg", "/felix2.jpg", "/felix3.jpg"],
        // },
        // {
        //     id: 2,
        //     paketId: 13,
        //     avatar: "/amelia.jpg",
        //     username: 'amelia',
        //     rating: 4,
        //     tanggalBerangkat: "2025-07-09",
        //     title: "Paon Happy Sharing Boat Watching Dolphin Only",
        //     text: "Seru banget! Lumba-lumbanya muncul cukup dekat dan pelampung tersedia untuk semua peserta, jadi aman. Guide lokalnya ramah dan selalu memantau kami selama perjalanan. Durasi 3 jam terasa pas untuk menikmati sunrise dan melihat lumba-lumba. Pengalaman yang menyenangkan dan memuaskan.",
        //     likes: 10,
        //     images: ["/amelia1.jpg", "/amelia2.jpg"],
        // },
        // {
        //     id: 3,
        //     paketId: 13,
        //     avatar: "/riski1.jpg",
        //     username: 'rizky',
        //     rating: 4,
        //     tanggalBerangkat: "2025-09-13",
        //     title: "Paon Happy Sharing Boat Watching Dolphin Only",
        //     text: "Tur ini menyenangkan dan harga cukup terjangkau. Perahu privat bikin suasana lebih nyaman meski sharing dengan peserta lain. Lumba-lumbanya terlihat jelas, dan guide selalu siap membantu. Sunrise pagi itu cantik banget. Hanya saja ombak agak besar, tapi keseluruhan tetap pengalaman yang seru!",
        //     likes: 10,
        //     images: ["/riski1.jpg"],
        // },
    ];

    export default cardReviewPaket13;