    const cardReviewPaket2 = [
            {
                id: 1,
                paketId: 2,
                avatar: "/paket2(3).jpg",
                username: 'Andi',
                rating: 5,
                tanggalBerangkat: "2025-09-13",
                title: "Seadolphine Lovina",
                text: "Pengalaman yang luar biasa bersama pemandu kami!! Kami berenang dengan snorkel bersama lumba-lumba yang berenang di samping kami, hanya berjarak dua kaki dari kami! Kami melihat banyak sekali lumba-lumba. Sangat direkomendasikan!",
                likes: 5,
                images: ["/reviewPaket2A(1).jpg","/reviewPaket2A(2).jpg"],
            },
            {
                id: 2,
                paketId: 2,
                avatar: "/paket1(2).jpg",
                username: 'Wijaya',
                rating: 5,
                tanggalBerangkat: "2025-09-13",
                title: "Seadolphine Lovina",
                text: "Pengalaman yang menyenangkan, tapi hati-hati dengan sengatan matahari!",
                likes: 3,
                images: ["/reviewPaket2B(1).webp", "/reviewPaket2B(2).webp", "/reviewPaket2B(3).webp"],
            },
            {
                id: 3,
                paketId: 2,
                avatar: "/paket2(1).jpg",
                username: 'Tiara Andin',
                rating: 5,
                tanggalBerangkat: "2025-09-11",
                title: "Seadolphine Lovina",
                text: "Pengalaman yang luar biasa, dilayani dengan baik. Banyak lumba-lumba yang terlihat berkat kapten kami yang hebat! Dia tahu cara menunjukkan lumba-lumba kepada kami setiap kali!",
                likes: 6,
                images: ["/reviewPaket2C(2).jpg", "/reviewPaket2C(3).jpg"],
            },
            {
                id: 4,
                paketId: 2,
                avatar: "/paket2(5).jpg",
                username: 'Aisyahhh ',
                rating: 5,
                tanggalBerangkat: "2025-09-10",
                title: "Seadolphine Lovina",
                text: "Perahu yang luar biasa. Banyak lumba-lumba di atas dan di bawah air. Air tenang dan perjalanan yang menenangkan. Saya sangat merekomendasikan meskipun ada banyak perahu.",
                likes: 6,
                images: [],
            },
            {
                id: 5,
                paketId: 2,
                avatar: "/paket2(4).jpg",
                username: 'RahmanTraveler',
                rating: 5,
                tanggalBerangkat: "2025-09-10",
                title: "Seadolphine Lovina",
                text: "Kami sangat senang dengan pengalaman kami bersama Seadolphin Lovina. Moy, pemandu kami, ramah dan bersahabat. Dia membawa kami berlayar ke tempat yang tidak banyak kapal lain. ",
                likes: 6,
                images: [],
            },
    ];

    export default cardReviewPaket2;